name: mobile
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.2
  go_router: ^14.2.8
  latlong2: ^0.9.1
  url_launcher: ^6.3.1
  flutter_markdown: ^0.7.4
  geolocator: ^13.0.1
  flutter_map_location_marker: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
